<%@ page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8"%>
<%@ include file="/WEB-INF/jsp/inc/taglib.jsp" %>
<html>
<head>
  <title>Ticket 管理</title>
  <%@ include file="/WEB-INF/jsp/inc/adminhead.jsp" %>
</head>
<body>
  <%@ include file="/WEB-INF/jsp/inc/adminnav.jsp" %>
   <div class="container">
     <div class="row">
       <div class="row">
	       <div class="col-md-12">
		     <h4>Ticket管理</h4>
		   </div>
	   </div> 
	   <form:form modelAttribute="ticketQuery" method="post" action="/admin/ticket/manage.html" cssClass="form-inline" role="form">
	   <div class="row myrow">
	   <div class="col-md-12">
	     
   			     <!--read only properties, generated by system-->
				<form:hidden path="pagination.rowCount"/>
				<form:hidden path="pagination.pageCount" id="pageCount"/>
				<!-- read only end -->
				<!--writable properties, control the currentpage, pagesize and order rule -->
				<form:hidden path="pagination.currentPage" id="currentPage"/>
				<form:hidden path="pagination.pageSize"/>
				<form:hidden path="orderByClause"/>
           <div class="form-group">
                <form:label path="title"  cssClass="sr-only">标题:</form:label>
                <form:input path="title" cssClass="form-control input-sm" placeholder="标题"/>
           </div>
           <div class="form-group">
                <form:label path="phone"  cssClass="sr-only">电话:</form:label>
                <form:input path="phone" cssClass="form-control input-sm" placeholder="电话"/>
           </div>         
           <div class="form-group">
                 <form:select path="status_code" cssClass="form-control input-sm">
                   <form:option value="">--所有状态--</form:option>
                   <form:options items="${applicationScope.ticketStatusMap}"/>
                 </form:select>
           </div>
             
           <button type="submit" class="btn btn-primary btn-sm">Search</button>	     
           <a href="/admin/ticket/create.html" class="btn btn-success btn-sm openEditPage">创建Ticket</a>
           
	    </div>
	   </div>
	   <div class="row myrow">
		   <div class="col-md-12">
			 <table class="table table-striped table-hover">
			    <tr>
			       <th><b>Ticket标题</b></th>
			       <th><b>客户姓名</b></th>
			       <th><b>联系电话</b></th>
			       <th><b>录入时间</b></th>
			       <th><b>更新时间</b></th>
			       <th><b>状态</b></th>
			       <th><b>客服</b></th>
			       <th><b>操作</b></th>
			    </tr>
			    <c:forEach items="${ticketmnglist}" var="var" varStatus="rowCounter">
			      <tr>  
		           <td>${var.title}</td>
			       <td>
			         ${var.last_name} ${var.first_name}
			       </td>
			       <td>
			         ${var.phone}
			       </td>
			       <td>
			         <fmt:formatDate value="${var.created_at}" pattern="MM/dd/YYYY HH:mm"/>
			       </td>
			       <td>
			         <fmt:formatDate value="${var.modified_at}" pattern="MM/dd/YYYY HH:mm"/>
			       </td>
			       <td>
			         <c:set var="status_code" value="${var.status_code}"/>
			         ${applicationScope.ticketStatusMap[status_code]}
			       </td>
			       <td>
			         <a href="../customerservice/detail.html?id=${var.processor_id}" target="../customerservice/detail">${var.processor_id}</a>
			       </td>	       
			       <td>
                     
                     	<c:choose>
  							<c:when test="${var.status_code =='10'|| var.status_code =='20'}">
  							<a class="openEditPage " href="operate.html?id=${var.id}&userLevel=${role}">
  							<span class="glyphicon glyphicon-edit text-success" title="处理"></span>  </a>
  							</c:when>  
  							<c:when test="${var.status_code =='30'&& role =='super'}">
  							<a class="openEditPage " href="operate.html?id=${var.id}&userLevel=${role}">
  							<span class="glyphicon glyphicon-edit text-success" title="处理"></span>  </a>
  							</c:when>
  							<c:when test="${var.status_code =='40'&& role =='super'}">
  							<a class="openEditPage " href="operate.html?id=${var.id}&userLevel=${role}">
  							<span class="glyphicon glyphicon-zoom-in text-info" title="查看"></span>  </a>
  							</c:when>
   							<c:otherwise>
   							 
   							 <a class="openEditPage " href="operate.html?id=${var.id}&userLevel=normal">
  							<span class="glyphicon glyphicon-zoom-in text-info" title="查看"></span>  </a>
   							 </c:otherwise> 
 						</c:choose>
                     
			       </td>			       
			      </tr>
			    </c:forEach>
			  </table> 
		   </div> 
	   </div>
	   
	   <div class="row myrow">
	     <div class="col-md-12">
	       <ul class="pagination pagination-sm" style="margin:0">
	         <li><a href="#" onclick="javascript:turnpage(-1)">&laquo;</a></li>
	         <c:forEach items="${pageNumList}" var="var" varStatus="rowCounter">
	         <li><a href="#" onclick="javascript:gotopage(${var})">${var}</a></li>
	         </c:forEach>
		     <li><a href="#" onclick="javascript:turnpage(1)">&raquo;</a></li>
			</ul>
	     </div>
	   </div>
	</form:form>	   
	
   </div><!-- row-fluid -->
	   
   </div>	
   <%@include file="/WEB-INF/jsp/inc/loadjs.jsp" %>
   <script type="text/javascript">
     function gotopage(pagenum){
    	 $("#currentPage").val(pagenum);
    	 document.forms[0].submit();
     }
     function turnpage(offset){
    	 var currentpage=parseInt($("#currentPage").val());
    	 var pagecount = parseInt($("#pageCount").val());
    	 currentpage += offset;
    	 $("#currentPage").val(currentpage);
    	 if(currentpage>0&&currentpage<=pagecount){
    	   document.forms[0].submit();
    	 }
     }
     
     function archiveUser(userid){
    	 if(confirm("删除后，只有系统管理员可以恢复. 确认删除吗?")){
    		 $.colorbox({iframe:true,fixed:true, href:"archiveUser.html?userid="+userid, width:"50%", height:"50%", onClosed:function(){ 
    			 document.forms[0].submit();
    		 }});
    	 }
     }     
     
     
     $(document).ready(function(){
    	 var currentpage=parseInt($("#currentPage").val());
    	 $(".pagination li:eq("+currentpage+")").addClass("active");
    	 
	    $(".openEditPage").colorbox({iframe:true, width:"90%", height:"90%", onClosed:function(){ 
	    	location.reload();
	    }});
	    
	    $(".openViewPage").colorbox({iframe:true, width:"90%", height:"90%", onClosed:function(){ } });
    	 
     });
   </script>
   
</body>
</html>