<%@ page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8"%>
<%@ include file="/WEB-INF/jsp/inc/taglib.jsp" %>
<html>
<head>
  <title>订单管理</title>
  <%@ include file="/WEB-INF/jsp/inc/adminhead.jsp" %>
  <link rel="stylesheet" href="/css/themes/base/jquery.ui.all.css">
</head>
<body>
  <%@ include file="/WEB-INF/jsp/inc/adminnav.jsp" %>
   <div class="container">
     <div class="row">
       <div class="row">
	       <div class="col-md-12">
		     <h4>订单管理</h4>		     		     
		   </div>
	   </div> 
	   <form:form modelAttribute="serviceOrderQuery" method="post" action="manage.html" cssClass="form-inline" role="form">
	   <div class="row myrow">
	   	<div class="col-md-12">	     
   			     <!--read only properties, generated by system-->
				<form:hidden path="pagination.rowCount"/>
				<form:hidden path="pagination.pageCount" id="pageCount"/>
				<!-- read only end -->
				<!--writable properties, control the current page, page size and order rule -->
				<form:hidden path="pagination.currentPage" id="currentPage"/>
				<form:hidden path="pagination.pageSize"/>
				<form:hidden path="orderByClause"/>
           <div class="form-group">
                <form:label path="order_id"  cssClass="sr-only">订单ID:</form:label>
                <form:input path="order_id" cssClass="form-control input-sm" placeholder="订单ID"/>
           </div>
           <div class="form-group">
                <form:label path="customer_member_id"  cssClass="sr-only">客户会员ID:</form:label>
                <form:input path="customer_member_id" cssClass="form-control input-sm" placeholder="客户会员ID"/>
           </div>
           <div class="form-group">
                <form:label path="business_member_id"  cssClass="sr-only">服务商会员ID:</form:label>
                <form:input path="business_member_id" cssClass="form-control input-sm" placeholder="服务商会员ID"/>
           </div>
       	</div>
       </div>
       <div class="row myrow">
	   	<div class="col-md-12">	          
           <div class="form-group">
                <form:label path="service_title"  cssClass="sr-only">服务名称:</form:label>
                <form:input path="service_title" cssClass="form-control input-sm" placeholder="服务名称"/>
           </div>
           <div class="form-group">
                 <form:label path="status_id"  cssClass="sr-only">订单状态:</form:label>
                 <form:select path="status_id" cssClass="form-control input-sm">
                   <form:option value="">--所有状态--</form:option>
                   <form:options items="${applicationScope.orderStatusMap}"/>
                 </form:select>
           </div>  
           <div class="form-group">
				<fmt:formatDate value="${serviceOrder.orderDateTimeFrom}" var="orderDateFrom" pattern="MM/dd/YYYY"/>
                <form:label path="orderDateTimeFrom"  cssClass="sr-only">订单时间:</form:label>
				<form:input path="orderDateTimeFrom" value = "${orderDateFrom}" cssClass="form-control input-sm" id="datepicker1" placeholder="订单创建自" />
           </div>                             
           <div class="form-group">
				<fmt:formatDate value="${serviceOrder.orderDateTimeTo}" var="orderDateTo" pattern="MM/dd/YYYY"/>
                <form:label path="orderDateTimeTo"  cssClass="sr-only">--</form:label>
				<form:input path="orderDateTimeTo" value = "${orderDateTo}" cssClass="form-control input-sm" id="datepicker2" placeholder="订单创建至" />
           </div>                             
           <button type="submit" class="btn btn-primary btn-sm">查询</button>
           <a id="creationlink" href="create.html" class="btn btn-success btn-sm openEditPage">增加新订单</a> 
        </div>
	   </div>
	   <div class="row myrow">
		   <div class="col-md-12">
			 <table class="table table-striped table-hover">
			    <tr>
			       <th><b>封面</b></th>
			       <th><b>订单ID</b></th>
			       <th><b>服务名称</b></th>
			       <th><b>状态分类</b></th>
			       <th><b>订单日期</b></th>
			       <th><b>时间</b></th>
			       <th><b>价格</b></th>
			       <th><b>服务商</b></th>
			       <th><b>消费者</b></th>
			       <th><b>操作</b></th>
			    </tr>
			    <c:forEach items="${serviceOrderList}" var="var" varStatus="rowCounter">
			      <tr>  
		           <td>
		           	<img alt="cover image" src="${var.cover_img}" height="60" width="60">		           	 
		           </td>
			       <td>
			         ${var.order_id}
			       </td>
			       <td>
			         ${var.service_title}
			       </td>
			       <td>
			         ${var.status}
			       </td>
			       <td>
			         ${var.orderDate}
			       </td>
			       <td>
			         ${var.orderTime}
			       </td>
			       <td>
			         $${var.priceTotal}
			       </td>
			       <td>
			         ${var.business_name}
			       </td>
			       <td>
			         ${var.first_name} ${var.last_name}
			       </td>
			       <td>
						<c:if test="${var.status_id=='10' || var.status_id=='20' || var.status_id=='30'}"> 
							<a class="openEditPage" href="update.html?order_id=${var.order_id}">
								<span class="glyphicon glyphicon-edit text-success" title="修改"></span>
							</a>
						</c:if> 
						<c:if test="${var.status_id=='60'}"> 
							<a class="openViewPage" href="vieworderrate.html?order_id=${var.order_id}">查看评价</a>
						</c:if> 
						<a class="openEditPage" href="copy.html?order_id=${var.order_id}">复制</a>
					</td>			       
			      </tr>
			    </c:forEach>
			  </table> 
		   </div> 
	   </div>
	   
	   <div class="row myrow">
	     <div class="col-md-12">
	       <ul class="pagination pagination-sm" style="margin:0">
	         <li><a href="#" onclick="javascript:turnpage(-1)">&laquo;</a></li>
	         <c:forEach items="${pageNumList}" var="var" varStatus="rowCounter">
	         <li><a href="#" onclick="javascript:gotopage(${var})">${var}</a></li>
	         </c:forEach>
		     <li><a href="#" onclick="javascript:turnpage(1)">&raquo;</a></li>
			</ul>
	     </div>
	   </div>
	</form:form>	   
	
   </div><!-- row-fluid -->
	   
   </div>	
   <%@include file="/WEB-INF/jsp/inc/loadjs.jsp" %>
   	<script src="/js/ui/jquery.ui.core.js"></script>
	<script src="/js/ui/jquery.ui.widget.js"></script>
	<script src="/js/ui/jquery.ui.datepicker.js"></script>
	<script type="text/javascript" src="/js/tinymce/tinymce.min.js"></script>
	<script type="text/javascript" src="/js/tinymce/tinymceinit.js"></script>
   	<script type="text/javascript">
     function gotopage(pagenum){
    	 $("#currentPage").val(pagenum);
    	 document.forms[0].submit();
     }
     function turnpage(offset){
    	 var currentpage=parseInt($("#currentPage").val());
    	 var pagecount = parseInt($("#pageCount").val());
    	 currentpage += offset;
    	 $("#currentPage").val(currentpage);
    	 if(currentpage>0&&currentpage<=pagecount){
    	   document.forms[0].submit();
    	 }
     }
     
     $(document).ready(function(){
    	 $("#datepicker1").datepicker(); 
    	 $("#datepicker2").datepicker();
    	 
    	 var currentpage=parseInt($("#currentPage").val());
    	 $(".pagination li:eq("+currentpage+")").addClass("active");
    	 
	    $(".openEditPage").colorbox({iframe:true, width:"80%", height:"90%", onClosed:function(){ 
	    	document.forms[0].submit();
	    }});
	    
	    $(".openViewPage").colorbox({iframe:true, width:"65%", height:"80%", onClosed:function(){ } });
    	 
     });
   </script>
   
</body>
</html>