<%@ page language="java" contentType="text/html; charset=utf-8"
	pageEncoding="utf-8"%>
<%@ include file="/WEB-INF/jsp/inc/taglib.jsp"%>
<html>
<head>
<title>用户账户管理</title>
<%@ include file="/WEB-INF/jsp/inc/adminhead.jsp"%>
<link href="/css/treeview.css" rel="stylesheet" />
</head>
<body>

	<%@ include file="/WEB-INF/jsp/inc/adminnav.jsp"%>
	<div class="container">
		<div class="row">
			<%@ include file="/WEB-INF/jsp/account/accountheader.jsp"%>
			<div class="row myrow">
				<div class="col-md-2"></div>
				<div class="col-md-10">
					<c:if test="${not empty account.feedbackMessage}">
						<div class="alert alert-success">${account.feedbackMessage}</div>
					</c:if>
				</div>
			</div>
			<div class="tab-content">
				<div role="tabpanel" class="tab-pane active" id="orderTab">
					<form:form modelAttribute="userOrderQueryType" method="post" action="order.html?id=${id}" cssClass="form-inline" role="form">
					   <div class="row myrow">
						   	<div class="col-md-12">
						   		<!--read only properties, generated by system-->
								<form:hidden path="unFinishedOrder.pagination.rowCount"/>
								<form:hidden path="unFinishedOrder.pagination.pageCount" id="pageCount1"/>
								<!-- read only end -->
								<!--writable properties, control the current page, page size and order rule -->
								<form:hidden path="unFinishedOrder.pagination.currentPage" id="currentPage1"/>
								<form:hidden path="unFinishedOrder.pagination.pageSize"/>
								<form:hidden path="unFinishedOrder.orderByClause"/>
						   	
					           <div class="form-group">
					                <form:label path="order_id"  cssClass="sr-only">订单ID:</form:label>
					                <form:input path="order_id" cssClass="form-control input-sm" placeholder="订单ID"/>
					           </div>
					           <div class="form-group">
					                <form:label path="service_title"  cssClass="sr-only">服务名称:</form:label>
					                <form:input path="service_title" cssClass="form-control input-sm" placeholder="服务名称"/>
					           </div>
	           					<button type="submit" class="btn btn-primary btn-sm">查询</button>
					       	</div>
				       </div>
				       
					   <h4>未完成订单</h4>
					   <div class="tablebox">
						 <table class="table table-striped table-hover">
						    <tr>
						       <th><b>封面</b></th>
						       <th><b>订单ID</b></th>
						       <th><b>服务名称</b></th>
						       <th><b>状态</b></th>
						       <th><b>服务日期</b></th>
						       <th><b>时间</b></th>
						       <th><b>价格</b></th>
						       <th><b>操作</b></th>
						    </tr>
						    <c:forEach items="${unfinishedOrderList}" var="var" varStatus="rowCounter1">
						      <tr>  
					           <td>
					           	<img alt="cover image" src="${var.cover_img}" height="60" width="60">		           	 
					           </td>
						       <td>
						         ${var.order_id}
						       </td>
						       <td>
						         ${var.service_title}
						       </td>
						       <td>
						         ${var.status}
						       </td>
						       <td>
						         ${var.serviceDateStr}
						       </td>
						       <td>
						         ${var.serviceTimeStr}
						       </td>
						       <td>
						         $${var.priceTotal}
						       </td>
						       <td>
									<c:if test="${var.status_id=='10' || var.status_id=='20' || var.status_id=='30'}"> 
										<a class="openEditPage" href="../serviceorder/cancel.html?order_id=${var.order_id}">取消</a>
									</c:if> 
									<a class="openEditPage" href="../serviceorder/copy.html?order_id=${var.order_id}">复制</a>
								</td>			       
						      </tr>
						    </c:forEach>
						  </table> 					
						</div>
						<div class="row myrow">
						     <div class="col-md-12">
						       <ul class="pagination pagination-sm" style="margin:0">
						         <li><a href="#" onclick="javascript:turnpage1(-1)">&laquo;</a></li>
						         <c:forEach items="${pageNumList1}" var="var" varStatus="rowCounter1">
						         <li><a href="#" onclick="javascript:gotopage1(${var})">${var}</a></li>
						         </c:forEach>
							     <li><a href="#" onclick="javascript:turnpage1(1)">&raquo;</a></li>
								</ul>
						     </div>
						</div>
						  						
						<div class="row myrow">
						   	 <div class="col-md-12">	     
				   			     <!--read only properties, generated by system-->
								<form:hidden path="finishedOrder.pagination.rowCount"/>
								<form:hidden path="finishedOrder.pagination.pageCount" id="pageCount2"/>
								<!-- read only end -->
								<!--writable properties, control the current page, page size and order rule -->
								<form:hidden path="finishedOrder.pagination.currentPage" id="currentPage2"/>
								<form:hidden path="finishedOrder.pagination.pageSize"/>
								<form:hidden path="finishedOrder.orderByClause"/>
					           	<div class="form-group">
					                 <form:label path="orderFinishedMonths"  cssClass="sr-only">已完成时间</form:label>
					                 <form:select path="orderFinishedMonths" cssClass="form-control input-sm">
					                   <form:options items="${serviceOrderFinishedPeriodMap}"/>
					                 </form:select>
					           </div>
	           				   <button type="submit" class="btn btn-primary btn-sm">查询</button>
					       	</div>
					    </div>
						<h4>已完成订单</h4>
						<div class="tablebox">
							 <table class="table table-striped table-hover">
							    <tr>
							       <th><b>封面</b></th>
							       <th><b>订单ID</b></th>
							       <th><b>服务名称</b></th>
							       <th><b>状态</b></th>
							       <th><b>服务日期</b></th>
							       <th><b>时间</b></th>
							       <th><b>价格</b></th>
							       <th><b>操作</b></th>
							    </tr>
							    <c:forEach items="${finishedOrderList}" var="var" varStatus="rowCounter2">
							      <tr>  
						           <td>
						           	<img alt="cover image" src="${var.cover_img}" height="60" width="60">		           	 
						           </td>
							       <td>
							         ${var.order_id}
							       </td>
							       <td>
							         ${var.service_title}
							       </td>
							       <td>
							         ${var.status}
							       </td>
							       <td>
							         ${var.serviceDateStr}
							       </td>
							       <td>
							         ${var.serviceTimeStr}
							       </td>
							       <td>
							         $${var.priceTotal}
							       </td>
							       <td>
										<c:if test="${var.status_id=='60'}"> 
											<a class="openViewPage" href="../serviceorder/vieworderrate.html?order_id=${var.order_id}">查看评价</a>
										</c:if> 
										<a class="openEditPage" href="../serviceorder/copy.html?order_id=${var.order_id}">复制</a>
									</td>			       
							      </tr>
							    </c:forEach>
							  </table> 	 
						</div>
						
						<div class="row myrow">
						     <div class="col-md-12">
						       <ul class="pagination pagination-sm" style="margin:0">
						         <li><a href="#" onclick="javascript:turnpage2(-1)">&laquo;</a></li>
						         <c:forEach items="${pageNumList2}" var="var" varStatus="rowCounter2">
						         <li><a href="#" onclick="javascript:gotopage2(${var})">${var}</a></li>
						         </c:forEach>
							     <li><a href="#" onclick="javascript:turnpage2(1)">&raquo;</a></li>
								</ul>
						     </div>
						  </div>			       
				     </form:form>
				</div>
			</div>
		</div>
	</div>
	<%@include file="/WEB-INF/jsp/inc/loadjs.jsp"%>
	<script type="text/javascript">
	    function gotopage1(pagenum){
		   	 $("#currentPage1").val(pagenum);
		   	 document.forms[0].submit();
		}
		function turnpage1(offset){
		   	 var currentpage=parseInt($("#currentPage1").val());
		   	 var pagecount = parseInt($("#pageCount1").val());
		   	 currentpage += offset;
		   	 $("#currentPage1").val(currentpage);
		   	 if(currentpage>0&&currentpage<=pagecount){
		   	   document.forms[0].submit();
		   	 }
		}
	    
	    function gotopage2(pagenum){
		   	 $("#currentPage2").val(pagenum);
		   	 document.forms[0].submit();
		}
		function turnpage2(offset){
		   	 var currentpage=parseInt($("#currentPage2").val());
		   	 var pagecount = parseInt($("#pageCount2").val());
		   	 currentpage += offset;
		   	 $("#currentPage2").val(currentpage);
		   	 if(currentpage>0&&currentpage<=pagecount){
		   	   document.forms[0].submit();
		   	 }
		}
	
		$(document).ready(function() {
	    	 var currentpage=parseInt($("#currentPage1").val());
	    	 $(".pagination li:eq("+currentpage+")").addClass("active");
	    	 
	    	 var currentpage=parseInt($("#currentPage2").val());
	    	 $(".pagination li:eq("+currentpage+")").addClass("active");
	    	 
			$(".openEditPage").colorbox({
				iframe : true,
				width : "80%",
				height : "90%",
				onClosed : function() {
					document.forms[0].submit();
				}
			});

			$(".openViewPage").colorbox({
				iframe : true,
				width : "80%",
				height : "90%",
				onClosed : function() {
				}
			});

		});
	</script>
</body>
</html>
