<%@ page language="java" contentType="text/html; charset=utf-8"
	pageEncoding="utf-8"%>
<%@ include file="/WEB-INF/jsp/inc/taglib.jsp"%>
<html>
<head>
<title>用户账户管理</title>
<%@ include file="/WEB-INF/jsp/inc/adminhead.jsp"%>
<link href="/css/treeview.css" rel="stylesheet" />
</head>
<body>

	<%@ include file="/WEB-INF/jsp/inc/adminnav.jsp"%>
	<div class="container">
		<div class="row">
			<div class="row">
				<div class="col-md-12">
					<h4>用户账户管理</h4>
				</div>
			</div>
			
			
			<div class="modal fade" id="confirm-delete" tabindex="-1"
				role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal"
								aria-hidden="true">&times;</button>
							<h4 class="modal-title" id="myModalLabel">Confirm Delete</h4>
						</div>

						<div class="modal-body">
							<p class="user-info"></p>
							<p>此操作将不能撤回，确定删除?</p>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-default"
								data-dismiss="modal">Cancel</button>
							<a href="#" class="btn btn-danger danger openEditPage" id="modal-delete" >Delete</a>
						</div>
					</div>
				</div>
			</div>
			
			<form:form modelAttribute="accountQuery" method="post" action="search.html" cssClass="form-inline" role="form">			
			   <div class="row myrow">
				   <div class="col-md-12">
				     
		   			     <!--read only properties, generated by system-->
						<form:hidden path="pagination.rowCount"/>
						<form:hidden path="pagination.pageCount" id="pageCount"/>
						<!-- read only end -->
						<!--writable properties, control the currentpage, pagesize and order rule -->
						<form:hidden path="pagination.currentPage" id="currentPage"/>
						<form:hidden path="pagination.pageSize"/>
						<form:hidden path="orderByClause"/>

						<div class="form-group">
			                <form:label path="phone"  cssClass="sr-only">电话号码:</form:label>
			                <form:input path="phone" cssClass="form-control input-sm" placeholder="电话号码"
			               />
			           	</div>
			           	<div class="form-group">
			                <form:label path="email"  cssClass="sr-only">邮件地址:</form:label>
			                <form:input path="email" cssClass="form-control input-sm" placeholder="邮件地址"
			               />
			           	</div>         
			           	<div class="form-group">
							<form:select path="status" cssClass="form-control input-sm">
                   				<form:option value="">--全部状态--</form:option>
                   				<form:options items="${accountStatusMap}"/>
                 			</form:select>
			           	</div>
			           	<button type="submit" class="btn btn-primary btn-sm">查询</button>	     
			           	<a href="create.html" class="btn btn-success btn-sm openEditPage">新建用户账号</a>
			           
				    </div>
				</div>
				<div class="row myrow">
				   	<div class="col-md-12">
					 	<table class="table table-striped table-hover">

						<tr>
							<th>姓名</th>
							<th>邮件</th>
							<th>手机</th>
							<th>会员类型</th>
							<th>语言</th>
							<th>账号状态</th>
							<th>性别</th>
							<th>生日</th>
							<th>操作</th>
						</tr>
						<c:forEach items="${accountList}" var="var" varStatus="rowCounter">
						<tr>
							<td><a href="detail.html?id=${var.id}" target="detail">${var.lastName} ${var.firstName}</a></td>
							<td><a href="mailto:${var.email}">${var.email}</a></td>
							<td>${var.phone}</td>
							<td><a href="membership.html?id=${var.id}" target="detail">查看</a></td>
							<td><c:set var="language_code" value="${var.preferredLanguage}"/>
			         		${languageMap[language_code]}</td>
							<td>
							<c:set var="status_code" value="${var.status}"/>
			         		 
			         		 <c:if test="${var.status==0}">
			               			<img src="/images/icon-fail.png">
					         </c:if>
					         <c:if test="${var.status==1}">
					               	<img src="/images/icon-ok.png">
					         </c:if>
					         <c:if test="${var.status==2}">
					               	<img src="/images/lock.png">
					         </c:if>
			         		
			         		</td>
							<td><c:set var="gender_code" value="${var.gender}"/>
			         		${genderMap[gender_code]}</td>
							<td><fmt:formatDate value="${var.birthday}" pattern="YYYY/MM/dd"/></td>
							<td><a href="detail.html?id=${var.id}" target="detail" >
							<span class="glyphicon glyphicon-th-list text-success" title="查看详情"></span></a>&nbsp;&nbsp;
							 <!--   <a href="delete/${var.id}.html" class="openEditPage btn btn-sm btn-warning"> -->
							    
							    <a data-href="delete/${var.id}.html"
										data-toggle="modal" data-target="#confirm-delete" href="#"
										id="delete-operate" title="${var.lastName} ${var.firstName}"  >
							    <span class="glyphicon glyphicon-trash text-danger" title="删除"></span></a></td>
						</tr>
						</c:forEach>
					</table>
					</div>
				</div>
			   <div class="row myrow">
			     <div class="col-md-12">
			       <ul class="pagination pagination-sm" style="margin:0">
			         <li><a href="#" onclick="javascript:turnpage(-1)">&laquo;</a></li>
			         <c:forEach items="${pageNumList}" var="var" varStatus="rowCounter">
			         <li><a href="#" onclick="javascript:gotopage(${var})">${var}</a></li>
			         </c:forEach>
				     <li><a href="#" onclick="javascript:turnpage(1)">&raquo;</a></li>
					</ul>
			     </div>
			   </div>
			</form:form>
		</div>
	</div>
	<%@include file="/WEB-INF/jsp/inc/loadjs.jsp"%>
	<script type="text/javascript">
	    function gotopage(pagenum){
	   	 	$("#currentPage").val(pagenum);
	   	 	document.forms[0].submit();
	    }
	    
	    function turnpage(offset){
		   	 var currentpage=parseInt($("#currentPage").val());
		   	 var pagecount = parseInt($("#pageCount").val());
		   	 currentpage += offset;
		   	 $("#currentPage").val(currentpage);
		   	 if(currentpage>0&&currentpage<=pagecount){
		   	   document.forms[0].submit();
		   	 }
	    }
	    
		$(document).ready(function() {
			
			
	    	var currentpage=parseInt($("#currentPage").val());
	    	$(".pagination li:eq("+currentpage+")").addClass("active");
	    	 
			$(".openEditPage").colorbox({
				iframe : true,
				width : "90%",
				height : "90%",
				onClosed : function() {
					document.forms[0].submit();
				}
			});
			
			$('#delete-operate ').click(function(){
				var user = $(this).attr('title');
				console.log("***********11"+user);
				
				$('#confirm-delete').on('show.bs.modal', function(e) {
				    $(this).find('.danger').attr('href', $(e.relatedTarget).data('href'));
				    $('.user-info').html('即将删除用户: <strong>' +user + '</strong>');
				});
				
				$('#modal-delete ').click(function(){
					$('#confirm-delete').modal('hide');
				});
			});
		});
	</script>
</body>
</html>
