<%@ page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8"%>
<%@ include file="/WEB-INF/jsp/inc/taglib.jsp" %>
<html>
<head>
  <title>服务产品管理</title>
  <%@ include file="/WEB-INF/jsp/inc/adminhead.jsp" %>
</head>
<body>
  <%@ include file="/WEB-INF/jsp/inc/adminnav.jsp" %>
   <div class="container">
     <div class="row">
       <div class="row">
	       <div class="col-md-12">
		     <h4>服务产品管理</h4>		     		     
		   </div>
	   </div>
	   
	   <div class="modal fade" id="confirm-delete" tabindex="-1"
			role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal"
							aria-hidden="true">&times;</button>
						<h4 class="modal-title" id="myModalLabel">确认删除</h4>
					</div>

					<div class="modal-body">
						<p class="user-info"></p>
						<p></p>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-default"
							data-dismiss="modal">取消</button>
						<a href="#" class="btn btn-danger danger openEditPage" id="modal-delete">删除</a>
					</div>
				</div>
			</div>
		</div>	   
	    
	   <form:form modelAttribute="serviceProductQuery" method="post" action="manage.html" cssClass="form-inline" role="form">
	   <div class="row myrow">
	   <div class="col-md-12">	     
   			     <!--read only properties, generated by system-->
				<form:hidden path="pagination.rowCount"/>
				<form:hidden path="pagination.pageCount" id="pageCount"/>
				<!-- read only end -->
				<!--writable properties, control the currentpage, pagesize and order rule -->
				<form:hidden path="pagination.currentPage" id="currentPage"/>
				<form:hidden path="pagination.pageSize"/>
				<form:hidden path="orderByClause"/>
           <div class="form-group">
                <form:label path="member_id"  cssClass="sr-only">服务商会员ID:</form:label>
                <form:input path="member_id" cssClass="form-control input-sm" placeholder="服务商会员ID"/>
           </div>
           <div class="form-group">
                <form:label path="service_title"  cssClass="sr-only">产品名称:</form:label>
                <form:input path="service_title" cssClass="form-control input-sm" placeholder="产品名称"/>
           </div>
           <div class="form-group">
           		<form:hidden path="category_id"/>
                <form:label path="category_id"  cssClass="sr-only">分类:</form:label>
                <form:input path="category_name" cssClass="form-control input-sm" placeholder="分类" readonly="true"/>
           </div>
           <a class="openViewPage btn btn-default btn-sm" href="choosecategory.html">浏览分类</a>
           <div class="form-group">
                 <form:label path="status_id"  cssClass="sr-only">状态:</form:label>
                 <form:select path="status_id" cssClass="form-control input-sm">
                   <form:option value="">--所有状态--</form:option>
                   <form:options items="${applicationScope.serviceStatusMap}"/>
                 </form:select>
           </div>                    
           <div class="form-group">
                 <form:label path="recommend_level_id"  cssClass="sr-only">推荐:</form:label>
                 <form:select path="recommend_level_id" cssClass="form-control input-sm">
                   <form:option value="">--所有推荐级别--</form:option>
                   <form:options items="${applicationScope.recommendLevelMap}"/>
                 </form:select>
           </div>                     
           <button type="submit" class="btn btn-primary btn-sm">查询</button>
           <a id="creationlink" href="create.html" class="btn btn-success btn-sm openEditPage">增加新服务产品</a> 
        </div>
	   </div>
	   <div class="row myrow">
		   <div class="col-md-12">
			 <table class="table table-striped table-hover">
			    <tr>
			       <th><b>封面</b></th>
			       <th><b>产品ID</b></th>
			       <th><b>产品名称</b></th>
			       <th><b>分类</b></th>
			       <th><b>服务商会员ID</b></th>
			       <th><b>状态</b></th>
			       <th><b>推荐</b></th>
			       <th><b>操作</b></th>
			    </tr>
			    <c:forEach items="${serviceProductList}" var="var" varStatus="rowCounter">
			      <tr>  
		           <td>
		           	<img alt="cover image" src="${var.cover_img}" height="60" width="60">		           	 
		           </td>
			       <td>
			         ${var.service_id}
			       </td>
			       <td>
			         ${var.service_title}
			       </td>
			       <td>
			         ${var.category_name}
			       </td>
			       <td>
			         ${var.member_id}
			       </td>
			       <td>
			         ${var.status}
			       </td>
			       <td>
			         ${var.recommend_level_name}
			       </td>
			       <td>
						<a class="openEditPage" href="update.html?service_id=${var.service_id}">
							<span class="glyphicon glyphicon-edit text-success" title="修改"></span>
						</a>
					 	<c:if test="${var.status_id=='20'}"> 
							<a class="openEditPage" href="../serviceorder/create.html?service_id=${var.service_id}">下订单</a>
						</c:if> 
						<a data-href="delete/${var.service_id}.html" data-toggle="modal" data-target="#confirm-delete" href="#" id="delete-operate" title="${var.service_id}">
							<span class="glyphicon glyphicon-trash text-danger" title="删除"></span>
						</a>
						<a href="../serviceorder/manage.html?service_id=${var.service_id}">订单列表</a>
					</td>			       
			      </tr>
			    </c:forEach>
			  </table> 
		   </div> 
	   </div>
	   
	   <div class="row myrow">
	     <div class="col-md-12">
	       <ul class="pagination pagination-sm" style="margin:0">
	         <li><a href="#" onclick="javascript:turnpage(-1)">&laquo;</a></li>
	         <c:forEach items="${pageNumList}" var="var" varStatus="rowCounter">
	         <li><a href="#" onclick="javascript:gotopage(${var})">${var}</a></li>
	         </c:forEach>
		     <li><a href="#" onclick="javascript:turnpage(1)">&raquo;</a></li>
			</ul>
	     </div>
	   </div>
	</form:form>	   
	
   </div><!-- row-fluid -->
	   
   </div>	
   <%@include file="/WEB-INF/jsp/inc/loadjs.jsp" %>
   <script type="text/javascript">
     function gotopage(pagenum){
    	 $("#currentPage").val(pagenum);
    	 document.forms[0].submit();
     }
     function turnpage(offset){
    	 var currentpage=parseInt($("#currentPage").val());
    	 var pagecount = parseInt($("#pageCount").val());
    	 currentpage += offset;
    	 $("#currentPage").val(currentpage);
    	 if(currentpage>0&&currentpage<=pagecount){
    	   document.forms[0].submit();
    	 }
     }
     
     $(document).ready(function(){
    	 var currentpage=parseInt($("#currentPage").val());
    	 $(".pagination li:eq("+currentpage+")").addClass("active");
    	 
	    $(".openEditPage").colorbox({iframe:true, width:"90%", height:"90%", onClosed:function(){ 
	    	document.forms[0].submit();
	    }});
	    
	    $(".openViewPage").colorbox({iframe:true, width:"90%", height:"90%", onClosed:function(){ } });
    	 
     });    
     
		$('#delete-operate ').click(function(){
			var user = $(this).attr('title');			
			
			$('#confirm-delete').on('show.bs.modal', function(e) {
			    $(this).find('.danger').attr('href', $(e.relatedTarget).data('href'));
			    $('.user-info').html('即将修改ID为: <strong>' +user + '</strong> 的服务产品状态为删除。您确定删除吗?');
			});
			
			$('#modal-delete ').click(function(){
				$('#confirm-delete').modal('hide');
			});
			
		});

   </script>
   
</body>
</html>