<%@ page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8"%>
<%@ include file="/WEB-INF/inc/taglib.jsp" %>
<html>
<head>
	<title>服务产品管理</title>
	<%@ include file="/WEB-INF/inc/head.jsp"%>
	<link rel="stylesheet" href="/css/themes/base/jquery.ui.all.css" />
</head>
<body>

   <div class="modal fade" id="confirm-delete" tabindex="-1"
		role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal"
						aria-hidden="true">&times;</button>
					<h4 class="modal-title" id="myModalLabel">确认删除</h4>
				</div>

				<div class="modal-body">
					<p class="user-info"></p>
					<p></p>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default"
						data-dismiss="modal">取消</button>
					<a href="#" class="btn btn-danger danger openEditPage" id="modal-delete">删除</a>
				</div>
			</div>
		</div>
	</div>	

	<div class="wrap">
		<!--globalnav start-->
		<%@ include file="/WEB-INF/inc/topnav.jsp"%>
		<!--globalnav end-->
		<!--globalnav start-->
		<%@ include file="/WEB-INF/inc/globalnav.jsp"%>
		<!--globalnav end-->
		
		<div class="container tbscontainer">
	    	<div class="main">
				<div class="row">
					<div class="col-sm-2">
		                <%@ include file="/WEB-INF/inc/leftbar.jsp"%>
		            </div>
				
					<!--<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main1">-->
					<div class="col-sm-10">
						<div class="row">
							<div class="col-sm-12">
								<div class="form-group">
									<h1 style="text-align:center;padding:20px">服务产品管理</h1>
								</div>
							</div>
						</div>
						<form:form modelAttribute="serviceProductQuery" method="post" action="manage.html" class="form-horizontal" role="form">
							<!--read only properties, generated by system-->
							<form:hidden path="pagination.rowCount"/>
							<form:hidden path="pagination.pageCount" id="pageCount"/>
							<!-- read only end -->
							<!--writable properties, control the currentpage, pagesize and order rule -->
							<form:hidden path="pagination.currentPage" id="currentPage"/>
							<form:hidden path="pagination.pageSize"/>
							<form:hidden path="orderByClause"/>
							<form:hidden path="user_id"/>
							
							<div class="row">
								<div class="col-sm-12 col-md-8">
									<div class="form-group">
										<label class="col-sm-12 col-md-3 control-label" id="ddid"  for="input-id" style="text-align:left">服务商会员ID</label>
										<div class="col-sm-10 col-md-6 dropdown">
											<div class="input-group">
												<form:select path="member_id" class="form-control dateSelector">
								                   <form:option value="">--所有服务商--</form:option>
								                   <form:options items="${memberIdTypeNameMap}"/>
								                 </form:select>										
											</div>
										</div>
										<div class="col-xs-12 col-sm-3 col-md-3">
											<div class="form-group">
												<div class="col-xs-12 col-sm-8 col-md-8">
													<button type="submit" class="btn btn-default">过滤</button>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="col-sm-12 col-md-4" style="text-align:right">
									<div class="form-group">
										<div class="col-xs-12 col-sm-8 col-md-8">
											<a class="openEditPage btn btn-default" href="create.html" >增加新服务产品</a>
										</div>
									</div>
								</div>
							</div>				
		
						</form:form>
						<!-----------表格1---------------------->
						<div class="row">
							<div class="col-sm-12">
								<div class="table-responsive">
									<table class="table table-bordered table-hover table-striped">
										<tr>
											<th>封面</th>
											<th>产品ID</th>
											<th>产品名称</th>
											<th>分类</th>
											<th>所属会员ID</th>
											<th>状态</th>
											<th>推荐</th>
											<th>操作</th>
										</tr>
										
										<c:forEach items="${serviceProductList}" var="var" varStatus="rowCounter">
									      	<tr>  
									           <td>
									           		<c:if test="${(empty var.cover_img)}">
									           			<a href="#"><img src="/images/no-image-found.jpg" width="100"/></a>
									           		</c:if>
									           		<c:if test="${(not empty var.cover_img)}">
									           			<img alt="cover image" src="${var.cover_img}" width="100">
									           		</c:if>						           			           	 
									           </td>
										       <td>
										         ${var.service_id}
										       </td>
										       <td>
										         ${var.service_title}
										       </td>
										       <td>
										         ${var.category_name}
										       </td>
										       <td>
										         ${var.member_id}
										       </td>
										       <td>
										         ${var.status}
										       </td>
										       <td>
										       		<c:set var="key">${var.recommend_level_id}</c:set>									       		
						         			 		${applicationScope.recommendLevelMap[key]}										       		
										       </td>
										       <td>
													<a class="openEditPage" href="update.html?service_id=${var.service_id}">
														<span class="glyphicon glyphicon-edit text-success" title="修改"></span>
													</a>
												 	<%-- <c:if test="${var.status_id=='20'}"> 
														<a class="openEditPage" href="../serviceorder/create.html?service_id=${var.service_id}">下订单</a>
													</c:if> --%> 
													<a data-href="delete/${var.service_id}.html" data-toggle="modal" data-target="#confirm-delete" href="#" id="delete-operate" title="${var.service_id}">
														<span class="glyphicon glyphicon-trash text-danger" title="删除"></span>
													</a>
													<c:if test="${var.status_id != '20'}">
														<a href="../serviceorder/manage.html?service_id=${var.service_id}">预览</a>
													</c:if>
												</td>			       
									      	</tr>
									    </c:forEach>
									</table>
								</div>
							</div>
						</div>
					
						<div class="row">
							<div class="col-sm-12">
								<nav style="float:right;">
									<ul class="pagination">
										<li><a href="#" onclick="javascript:turnpage(-1)">&laquo;</a></li>
								        <c:forEach items="${pageNumList}" var="var" varStatus="rowCounter">
								        <li><a href="#" onclick="javascript:gotopage(${var})">${var}</a></li>
								        </c:forEach>
									    <li><a href="#" onclick="javascript:turnpage(1)">&raquo;</a></li>
									</ul>
								</nav>
							</div>
						</div>
					</div>
				
				</div>
			</div>
		</div>
		
		<!--#include file="footer.shtml" -->	
	</div>
	   	
	<%@include file="/WEB-INF/inc/globalfooter.jsp"%>
	<%@include file="/WEB-INF/inc/loadjs.jsp"%>
	<script src="/js/ui/jquery.ui.core.js"></script>
	<script src="/js/ui/jquery.ui.widget.js"></script>
	<script src="/js/ui/jquery.ui.datepicker.js"></script>
   <script type="text/javascript">
     function gotopage(pagenum){
    	 $("#currentPage").val(pagenum);
    	 document.forms[0].submit();
     }
     function turnpage(offset){
    	 var currentpage=parseInt($("#currentPage").val());
    	 var pagecount = parseInt($("#pageCount").val());
    	 currentpage += offset;
    	 $("#currentPage").val(currentpage);
    	 if(currentpage>0&&currentpage<=pagecount){
    	   document.forms[0].submit();
    	 }
     }
     
     $(document).ready(function(){
    	 var currentpage=parseInt($("#currentPage").val());
    	 $(".pagination li:eq("+currentpage+")").addClass("active");
    	 
	    $(".openEditPage").colorbox({iframe:true, width:"90%", height:"90%", onClosed:function(){ 
	    	document.forms[0].submit();
	    }});
	    
	    $(".openViewPage").colorbox({iframe:true, width:"90%", height:"90%", onClosed:function(){ } });
    	 
     });    
     
		$('#delete-operate ').click(function(){
			var user = $(this).attr('title');			
			
			$('#confirm-delete').on('show.bs.modal', function(e) {
			    $(this).find('.danger').attr('href', $(e.relatedTarget).data('href'));
			    $('.user-info').html('即将修改ID为: <strong>' +user + '</strong> 的服务产品状态为删除。您确定删除吗?');
			});
			
			$('#modal-delete ').click(function(){
				$('#confirm-delete').modal('hide');
			});
			
		});

   </script>
   
</body>
</html>