<%@ page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8"%>
<%@ include file="/WEB-INF/jsp/inc/taglib.jsp" %>
<html>
<head>
  <title>新服务商查询</title>
  <%@ include file="/WEB-INF/jsp/inc/adminhead.jsp" %>
</head>
<body>  
   <div class="container">
   
   	   <div class="modal fade" id="confirm-delete" tabindex="-1"
			role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal"
							aria-hidden="true">&times;</button>
						<h4 class="modal-title" id="myModalLabel">确认删除</h4>
					</div>

					<div class="modal-body">
						<p class="user-info"></p>
						<p></p>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-default"
							data-dismiss="modal">取消</button>
						<a href="#" class="btn btn-danger danger openEditPage" id="modal-delete">删除</a>
					</div>
				</div>
			</div>
		</div>	
   
     <div class="row">
       <div class="row">
	       <div class="col-md-12">
		     <h4>新服务商查询</h4>
		   </div>
	   </div> 
	   <form:form modelAttribute="businessProfileQuery" method="post" action="manage.html" cssClass="form-inline" role="form">
	   <div class="row myrow">
	   <div class="col-md-12">	     
   			     <!--read only properties, generated by system-->
				<form:hidden path="pagination.rowCount"/>
				<form:hidden path="pagination.pageCount" id="pageCount"/>
				<!-- read only end -->
				<!--writable properties, control the currentpage, pagesize and order rule -->
				<form:hidden path="pagination.currentPage" id="currentPage"/>
				<form:hidden path="pagination.pageSize"/>
				<form:hidden path="orderByClause"/>
           <div class="form-group">
                <form:label path="member_id"  cssClass="sr-only">新服务商ID:</form:label>
                <form:input path="member_id" cssClass="form-control input-sm" placeholder="新服务商ID"/>
           </div>
           <div class="form-group">
                <form:label path="business_name"  cssClass="sr-only">公司名:</form:label>
                <form:input path="business_name" cssClass="form-control input-sm" placeholder="公司名"/>
           </div>
           <div class="form-group">
                <form:label path="phone"  cssClass="sr-only">手机号码:</form:label>
                <form:input path="phone" cssClass="form-control input-sm" placeholder="手机号码"/>
           </div>         
           <button type="submit" class="btn btn-primary btn-sm">查询</button>
           <a id="creationlink" href="create.html"
					class="btn btn-success btn-sm openEditPage">新建服务商</a>
					 
        </div>
	   </div>
	   <div class="row myrow">
		   <div class="col-md-12">
			 <table class="table table-striped table-hover">
			    <tr>
			       <th><b>新服务商ID</b></th>
			       <th><b>公司名称</b></th>
			       <th><b>公司负责人</b></th>
			       <th><b>手机号码</b></th>
			       <th><b>公司地址</b></th>
			       <th><b>公司开始于</b></th>
			       <th><b>操作</b></th>
			    </tr>
			    <c:forEach items="${businessProfileList}" var="var" varStatus="rowCounter">
			      <tr>  
		           <td>${var.member_id}</td>
			       <td>
			         ${var.business_name}
			       </td>
			       <td>
			         ${var.owner_name}
			       </td>
			       <td>
			         ${var.phone}
			       </td>
			       <td>
			         ${var.address}
			       </td>
			       <td>
			         <fmt:formatDate value="${var.business_start}" pattern="MM/dd/YYYY"/>
			       </td>
			       <td>
					 <a class="openEditPage" href="update.html?member_id=${var.member_id}">
						<span class="glyphicon glyphicon-edit text-success" title="修改"></span>
					</a>
				 	<a data-href="delete/${var.member_id}.html" data-toggle="modal" data-target="#confirm-delete" href="#" id="delete-operate" title="${var.member_id}">
						<span class="glyphicon glyphicon-trash text-danger" title="删除"></span>
					</a>				
				   </td>			       
			      </tr>
			    </c:forEach>
			  </table> 
		   </div> 
	   </div>
	   
	   <div class="row myrow">
	     <div class="col-md-12">
	       <ul class="pagination pagination-sm" style="margin:0">
	         <li><a href="#" onclick="javascript:turnpage(-1)">&laquo;</a></li>
	         <c:forEach items="${pageNumList}" var="var" varStatus="rowCounter">
	         <li><a href="#" onclick="javascript:gotopage(${var})">${var}</a></li>
	         </c:forEach>
		     <li><a href="#" onclick="javascript:turnpage(1)">&raquo;</a></li>
			</ul>
	     </div>
	   </div>
	</form:form>	   
	
   </div><!-- row-fluid -->
	   
   </div>	
   <%@include file="/WEB-INF/jsp/inc/loadjs.jsp" %>
   <script type="text/javascript">
     function gotopage(pagenum){
    	 $("#currentPage").val(pagenum);
    	 document.forms[0].submit();
     }
     function turnpage(offset){
    	 var currentpage=parseInt($("#currentPage").val());
    	 var pagecount = parseInt($("#pageCount").val());
    	 currentpage += offset;
    	 $("#currentPage").val(currentpage);
    	 if(currentpage>0&&currentpage<=pagecount){
    	   document.forms[0].submit();
    	 }
     }
     
     $(document).ready(function(){
    	 var currentpage=parseInt($("#currentPage").val());
    	 $(".pagination li:eq("+currentpage+")").addClass("active");
    	 
	    $(".openEditPage").colorbox({iframe:true, width:"90%", height:"90%", onClosed:function(){ 
	    	document.forms[0].submit();
	    }});
	    
	    $(".openViewPage").colorbox({iframe:true, width:"90%", height:"90%", onClosed:function(){ } });
    	 
     });
     
		$('#delete-operate ').click(function(){
			var user = $(this).attr('title');			
			
			$('#confirm-delete').on('show.bs.modal', function(e) {
			    $(this).find('.danger').attr('href', $(e.relatedTarget).data('href'));
			    $('.user-info').html('即将删除ID为: <strong>' +user + '</strong> 的新服务商。 删除后需要联系管理员才能恢复数据，您确定删除吗?');
			});
			
			$('#modal-delete ').click(function(){
				$('#confirm-delete').modal('hide');
			});
			
		});
   </script>
   
</body>
</html>