<%@ page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8"%>
<%@ include file="/WEB-INF/jsp/inc/taglib.jsp" %>
<html>
<head>
  <title>后台管理系统</title>
  <%@ include file="/WEB-INF/jsp/inc/adminhead.jsp" %>
</head>
<body>
  <%@ include file="/WEB-INF/jsp/inc/adminnav.jsp" %>
   <div class="container">
     <div class="row">
       <div class="row">
	       <div class="col-md-12">
		     <h4>用户帐号管理</h4> 
		   </div>
	   </div> 
	   <form:form modelAttribute="userQuery" method="post" action="usermng.html" cssClass="form-inline" role="form">
	   <div class="row myrow">
	   <div class="col-md-12">
	     
   			     <!--read only properties, generated by system-->
				<form:hidden path="pagination.rowCount"/>
				<form:hidden path="pagination.pageCount" id="pageCount"/>
				<!-- read only end -->
				<!--writable properties, control the currentpage, pagesize and order rule -->
				<form:hidden path="pagination.currentPage" id="currentPage"/>
				<form:hidden path="pagination.pageSize"/>
				<form:hidden path="orderByClause"/>
           <div class="form-group">
                <form:label path="firstname"  cssClass="sr-only">名:</form:label>
                <form:input path="firstname" cssClass="form-control input-sm" placeholder="First Name"/>
           </div>
           <div class="form-group">
                <form:label path="lastname"  cssClass="sr-only">姓:</form:label>
                <form:input path="lastname" cssClass="form-control input-sm" placeholder="Last Name"/>
           </div>
           <div class="form-group">
                 <form:label path="phone"  cssClass="sr-only">电话:</form:label>
                 <form:input path="phone" cssClass="form-control input-sm" placeholder="Phone"/>
           </div>
		   <div class="form-group">
		       <form:label path="email"  cssClass="sr-only">Email:</form:label>
               <form:input path="email" cssClass="form-control input-sm" placeholder="Email"/>
           </div>           
           <div class="form-group">
                 <form:select path="usertype" cssClass="form-control input-sm">
                   <form:option value="">--用户类型--</form:option>
                   <form:options items="${userQuery.usertypelist}"/>

                 </form:select>
           </div>  
           <div class="form-group">
                 <form:select path="status" cssClass="form-control input-sm">
                   <form:option value="-1">--帐号状态--</form:option>
                   <form:option value="0">未激活</form:option>
                   <form:option value="1">激活</form:option>
                   <form:option value="2">锁定</form:option>
                 </form:select>
           </div>    
           <button type="submit" class="btn btn-primary btn-sm">Search</button>	     
           <a href="adduser.html" class="btn btn-success btn-sm openEditPage">新建用户</a>
	    </div>
	   </div>
	   <div class="row myrow">
		   <div class="col-md-12">
			 <table class="table table-striped table-hover">
			    <tr>
			       <th><b>姓名</b></th>
			       <th><b>类型</b></th>
			       <th><b>角色</b></th>
			       <th><b>状态</b></th>
			       <th><b>Email</b></th>
			       <th><b>电话</b></th>
			       <th><b>生日</b></th>
			       <th><b>性别</b></th>
			       <th><b>注册日期</b></th>
			       <th><b>操作</b></th>
			    </tr>
			    <c:forEach items="${usermnglist}" var="var" varStatus="rowCounter">
			      <tr>  
		           <td>${var.firstname} ${var.lastname}</td>
			       <td>
			          <c:set var="usertype" value="${var.usertype}"/>
	                  ${var.usertypelist[usertype]}
			       </td>
			       <td>
			         ${var.role}
			       </td>
			       <td>
			         <c:if test="${var.status==0}">
			               	<img src="/images/icon-fail.png">
			         </c:if>
			         <c:if test="${var.status==1}">
			               	<img src="/images/icon-ok.png">
			         </c:if>
			         <c:if test="${var.status==2}">
			               	<img src="/images/lock.png">
			         </c:if>
			       </td>
			       <td>
			         ${var.email}
			       </td>
			       <td>
			         ${var.phone}
			       </td>
			       <td>
			         <fmt:formatDate value="${var.birth}" pattern="MM/dd/YYYY"/>
			       </td>
			       <td>${var.sex}</td>
			       <td>
			         <fmt:formatDate value="${var.inputtime}" pattern="MM/dd/YYYY"/>
			       </td>			       
			       <td>
                      <!--<a class="openEditPage" href="updateuser.html?userid=${var.userid}">修改</a>-->
			       </td>			       
			      </tr>
			    </c:forEach>
			  </table> 
		   </div>
	   </div>
	   
	   <div class="row myrow">
	     <div class="col-md-12">
	       <ul class="pagination pagination-sm" style="margin:0">
	         <li><a href="#" onclick="javascript:turnpage(-1)">&laquo;</a></li>
	         <c:forEach items="${pageNumList}" var="var" varStatus="rowCounter">
	         <li><a href="#" onclick="javascript:gotopage(${var})">${var}</a></li>
	         </c:forEach>
		     <li><a href="#" onclick="javascript:turnpage(1)">&raquo;</a></li>
			</ul>
	     </div>
	   </div>
	</form:form>	   
	
   </div><!-- row-fluid -->
	   
   </div>	
   <%@include file="/WEB-INF/jsp/inc/loadjs.jsp" %>
   <script type="text/javascript">
     function gotopage(pagenum){
    	 $("#currentPage").val(pagenum);
    	 document.forms[0].submit();
     }
     function turnpage(offset){
    	 var currentpage=parseInt($("#currentPage").val());
    	 var pagecount = parseInt($("#pageCount").val());
    	 currentpage += offset;
    	 $("#currentPage").val(currentpage);
    	 if(currentpage>0&&currentpage<=pagecount){
    	   document.forms[0].submit();
    	 }
     }
     
     function archiveUser(userid){
    	 if(confirm("删除后，只有系统管理员可以恢复. 确认删除吗?")){
    		 $.colorbox({iframe:true,fixed:true, href:"archiveUser.html?userid="+userid, width:"50%", height:"50%", onClosed:function(){ 
    			 document.forms[0].submit();
    		 }});
    	 }
     }     
     
     $(document).ready(function(){
    	 var currentpage=parseInt($("#currentPage").val());
    	 $(".pagination li:eq("+currentpage+")").addClass("active");
    	 
	    $(".openEditPage").colorbox({iframe:true, width:"90%", height:"90%", onClosed:function(){ 
	    	document.forms[0].submit();
	    }});
	    
	    $(".openViewPage").colorbox({iframe:true, width:"90%", height:"90%", onClosed:function(){ } });
    	 
     });
   </script>
   
</body>
</html>