<%@ page language="java" contentType="text/html; charset=utf-8"
	pageEncoding="utf-8"%>
<%@ include file="/WEB-INF/jsp/inc/taglib.jsp"%>
<html>
<head>
<title>浏览用户</title>
<%@ include file="/WEB-INF/jsp/inc/adminhead.jsp"%>
<link rel="stylesheet" href="/css/themes/base/jquery.ui.all.css">
<style type="text/css">
.checkboxdiv {
	display: inline-block;
	width: 120px;
}
</style>
</head>
<body>

	<div class="container">
		<div class="row">
			<div class="row">
				<div class="col-md-12">
					<h4>浏览用户</h4>
				</div>
			</div>
			<form:form modelAttribute="accountQuery" method="post"
				action="chooseuser.html" cssClass="form-inline" role="form">
				<div class="row myrow">
					<div class="col-md-12">

						<!--read only properties, generated by system-->
						<form:hidden path="pagination.rowCount" />
						<form:hidden path="pagination.pageCount" id="pageCount" />
						<!-- read only end -->
						<!--writable properties, control the currentpage, pagesize and order rule -->
						<form:hidden path="pagination.currentPage" id="currentPage" />
						<form:hidden path="pagination.pageSize" />
						<form:hidden path="orderByClause" />

						<div class="form-group">
							<form:label path="phone" cssClass="sr-only">电话号码:</form:label>
							<form:input path="phone" cssClass="form-control input-sm"
								placeholder="电话号码" />
						</div>
						<div class="form-group">
							<form:label path="email" cssClass="sr-only">邮件地址:</form:label>
							<form:input path="email" cssClass="form-control input-sm"
								placeholder="邮件地址" />
						</div>

						<button type="submit" class="btn btn-primary btn-sm">查询</button>

					</div>
				</div>
				<div class="row myrow">
					<div class="col-md-12">
						<table class="table table-striped table-hover">

							<tr>
								<th></th>
								<th>ID</th>
								<th>姓名</th>
								<th>邮件</th>
								<th>手机</th>
								<th>生日</th>
								<th>帐号状态</th>
							</tr>
							<c:forEach items="${accountList}" var="var"
								varStatus="rowCounter">
								<tr>
									<td>
										<div class="radio">
											<label><input type="radio" name="user_id"
												value="${var.id}" alt="${var.lastName}"></label>
										</div>
									</td>
									<td>${var.id}</td>
									<td>${var.lastName}${var.firstName}</td>
									<td>${var.email}</td>
									<td>${var.phone}</td>
									<td><fmt:formatDate value="${var.birthday}"
											pattern="YYYY/MM/dd" /></td>
									<td><c:set var="status_code" value="${var.status}" />
										${accountStatusMap[status_code]}</td>



								</tr>
							</c:forEach>
						</table>
					</div>
				</div>
				<div class="row myrow">
					<div class="col-md-12">
						<ul class="pagination pagination-sm" style="margin: 0">
							<li><a href="#" onclick="javascript:turnpage(-1)">&laquo;</a></li>
							<c:forEach items="${pageNumList}" var="var"
								varStatus="rowCounter">
								<li><a href="#" onclick="javascript:gotopage(${var})">${var}</a></li>
							</c:forEach>
							<li><a href="#" onclick="javascript:turnpage(1)">&raquo;</a></li>
						</ul>
					</div>
				</div>

			</form:form>

			<div class="row myrow">
				<div class="col-md-12" style="text-align: center">
					<button type="button" id="addbutton">确定</button>
					<span id="resultmsg"></span>
				</div>

			</div>

		</div>
	</div>
	<%@include file="/WEB-INF/jsp/inc/loadjs.jsp"%>
	<script src="/js/ui/jquery.ui.core.js"></script>
	<script src="/js/ui/jquery.ui.widget.js"></script>
	<script src="/js/ui/jquery.ui.datepicker.js"></script>
	<script type="text/javascript" src="/js/tinymce/tinymce.min.js"></script>
	<script type="text/javascript" src="/js/tinymce/tinymceinit.js"></script>
	<script type="text/javascript">
	    function gotopage(pagenum){
	   	 	$("#currentPage").val(pagenum);
	   	 	document.forms[0].submit();
	    }
	    
	    function turnpage(offset){
		   	 var currentpage=parseInt($("#currentPage").val());
		   	 var pagecount = parseInt($("#pageCount").val());
		   	 currentpage += offset;
		   	 $("#currentPage").val(currentpage);
		   	 if(currentpage>0&&currentpage<=pagecount){
		   	   document.forms[0].submit();
		   	 }
	    }
	    
		$(document).ready(function() {
	    	var currentpage=parseInt($("#currentPage").val());
	    	$(".pagination li:eq("+currentpage+")").addClass("active");
	    	 
			$(".openEditPage").colorbox({
				iframe : true,
				width : "90%",
				height : "90%",
				onClosed : function() {
					document.forms[0].submit();
				}
			});
			
		});
		
		$(function(){
			
			$("#addbutton").click(function(){
				
				var user_id = $("input:radio[name=user_id]:checked").val();
				parent.$("#user_id").val(user_id).trigger('change');
				parent.jQuery.colorbox.close();		
			});
			
			
		});
	</script>
</body>
</html>
