<%@ page language="java" contentType="text/html; charset=utf-8"
	pageEncoding="utf-8"%>
<%@ include file="/WEB-INF/jsp/inc/taglib.jsp"%>
<html>
<head>
<title>浏览服务产品</title>
<%@ include file="/WEB-INF/jsp/inc/adminhead.jsp"%>
<link rel="stylesheet" href="/css/themes/base/jquery.ui.all.css">
<style type="text/css">
.checkboxdiv {
	display: inline-block;
	width: 120px;
}
</style>
</head>
<body>

	<div class="container">
		<div class="row">
			<div class="row">
				<div class="col-md-12">
					<h4>浏览服务产品</h4>
				</div>
			</div>
			<form:form modelAttribute="serviceProductQuery" method="post"
				action="serviceproduct.html" cssClass="form-inline" role="form">
				<div class="row myrow">
					<div class="col-md-12">

						<!--read only properties, generated by system-->
						<form:hidden path="pagination.rowCount" />
						<form:hidden path="pagination.pageCount" id="pageCount" />
						<!-- read only end -->
						<!--writable properties, control the currentpage, pagesize and order rule -->
						<form:hidden path="pagination.currentPage" id="currentPage" />
						<form:hidden path="pagination.pageSize" />
						<form:hidden path="orderByClause" />

						<div class="form-group">
							<form:label path="member_id" cssClass="sr-only">服务商会员ID:</form:label>
							<form:input path="member_id" cssClass="form-control input-sm"
								placeholder="服务商会员" />
						</div>
						<div class="form-group">
							<form:label path="service_title" cssClass="sr-only">产品名称:</form:label>
							<form:input path="service_title" cssClass="form-control input-sm"
								placeholder="产品名称" />
						</div>

						<button type="submit" class="btn btn-primary btn-sm">查询</button>

					</div>
				</div>
				<div class="row myrow">
					<div class="col-md-12">
						<table class="table table-striped table-hover">

							<tr>
								<th></th>
								<th>封面</th>
								<th>产品ID</th>
								<th>产品名称</th>
								<th>分类</th>
								<th>服务商会员ID</th>
								<th>状态</th>
								<th>推荐</th>
							</tr>
							<c:forEach items="${serviceProductList}" var="var"
								varStatus="rowCounter">
								<tr>
									<td>
										<div class="radio">
											<label><input type="radio" name="service_id"
												value="${var.service_id}" alt="${var.service_title}"></label>
										</div>
									</td>
									<td>
										<img alt="cover image" src="${var.cover_img}" height="60" width="60">
									</td>
									<td>
										${var.service_id}
									</td>
									<td>
										<a href="#">${var.service_title}</a>
									</td>
									<td>
			        				   	${var.category_name}
			       					</td>
									<td>
			         					${var.member_id}
			       					</td>
							       	<td>
							         	${var.status}
							       	</td>
							       	<td>
							         	${var.recommend_level_name}
							       	</td>
							 	</tr>
							</c:forEach>
						</table>
					</div>
				</div>
				<div class="row myrow">
					<div class="col-md-12">
						<ul class="pagination pagination-sm" style="margin: 0">
							<li><a href="#" onclick="javascript:turnpage(-1)">&laquo;</a></li>
							<c:forEach items="${pageNumList}" var="var"
								varStatus="rowCounter">
								<li><a href="#" onclick="javascript:gotopage(${var})">${var}</a></li>
							</c:forEach>
							<li><a href="#" onclick="javascript:turnpage(1)">&raquo;</a></li>
						</ul>
					</div>
				</div>
			</form:form>
			<div class="row myrow">
				<div class="col-md-12" style="text-align: center">
					<button type="button" id="addbutton">确定</button>
					<span id="resultmsg"></span>
				</div>
			</div>

		</div>
	</div>
	<%@include file="/WEB-INF/jsp/inc/loadjs.jsp"%>
	<script src="/js/ui/jquery.ui.core.js"></script>
	<script src="/js/ui/jquery.ui.widget.js"></script>
	<script src="/js/ui/jquery.ui.datepicker.js"></script>
	<script type="text/javascript" src="/js/tinymce/tinymce.min.js"></script>
	<script type="text/javascript" src="/js/tinymce/tinymceinit.js"></script>
	<script type="text/javascript">
	    function gotopage(pagenum){
	   	 	$("#currentPage").val(pagenum);
	   	 	document.forms[0].submit();
	    }
	    
	    function turnpage(offset){
		   	 var currentpage=parseInt($("#currentPage").val());
		   	 var pagecount = parseInt($("#pageCount").val());
		   	 currentpage += offset;
		   	 $("#currentPage").val(currentpage);
		   	 if(currentpage>0&&currentpage<=pagecount){
		   	   document.forms[0].submit();
		   	 }
	    }
	    
		$(document).ready(function() {
	    	var currentpage=parseInt($("#currentPage").val());
	    	$(".pagination li:eq("+currentpage+")").addClass("active");
	    	 
			$(".openEditPage").colorbox({
				iframe : true,
				width : "90%",
				height : "90%",
				onClosed : function() {
					document.forms[0].submit();
				}
			});			
		});
		
		$(function(){			
			$("#addbutton").click(function(){
				
				var service_id = $("input:radio[name=service_id]:checked").val();
				
				if(service_id == null){
					alert("请选择服务产品");
				}else{
					parent.$("#service_id").val(service_id).trigger('change');
					parent.jQuery.colorbox.close();	
				}			
					
			});			
		});
	</script>
</body>
</html>
